### PR TITLE
add a boolean() method to turn perl true/false into JSON true/false

### PR DESCRIPTION
**Pull request by davidcantrelluk2**
Patch to solve [issue 40](https://github.com/makamaka/JSON/issues/40)

### CODE REVIEW

**Comment by charsbar** [comment]
Thanks!

**Comment by DrHyde** [comment]
Thank *you*. Got an estimate for when there will be a release and I can start deleting my ternaries?

**Comment by charsbar** [comment]
Hopefully tomorrow, or maybe this weekend, when I finish updating the pod and my authoring tool to sync with JSON::XS/JSON::PP.

**Comment by charsbar** [comment]
Shipped 4.01.

**Comment by DrHyde** [comment]
Thanks!

**Pull request merged**
